### ISSUE TITLE
Make Alert Webpages

### ISSUE THREAD

**Issue by habig** [SNEWS2/SNEWS_Coincidence_System#56] opened 2023-06-02 09:10 UTC
Alerts should each get a webpage.  This allows updates to write to that webpage, healpix maps to be posted, etc.  Ideally an alert should send out one email/GCN/etc, that all refer to this webpage.  Prevents confusing spam as more info comes in.

There has to be a kafka module that writes html based on what comes into a channel, that's how web interfaces to, say, twitter work.  So, this issue is probably separate from CS other than that it cosumes the alert channel output, and the URL to build needs to be supplied by CS.

**Comment by habig** [comment] 2023-06-02 09:19
Googling around, there are commercial kafka/Wordpress integrations.  I suspect if we want to use open source stuff, the main wordpress-powered site might have to point to bare apache somewhere for us to work.

Tagging @mlinvill to see if he has any ideas.

**Comment by habig** [comment] 2023-10-27 12:24
Notes from today's meeting: the idea to replace mongo with sqllite might make this a very helpful tool to build the alert webpage.

**Comment by KaraMelih** [comment] 2024-08-14 20:22
Duplicate of #59, since the other one is more up to date, closing this one

**Closed by KaraMelih** 2024-08-14 20:22 UTC
Labels: enhancement
